name: End to end tests

# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: [deployment_status]
jobs:
  tests:
    # only runs this job on successful deploy
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Run Cypress ðŸŒ²
        uses: cypress-io/github-action@v4.1.1
        with:
          config: baseUrl=${{ github.event.deployment_status.target_url }}
      - name: Upload video ðŸ“¼
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test videos
          path: cypress/videos
          retention-days: 14
